#!/bin/bash

# Run this after flashing the Beaglebone with Debian

# update
apt-get update

# install node dependencies
apt-get install -y gcc g++ clang curl

# build and install node
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
/root/.nvm/nvm.sh install stable
/root/.nvm/nvm.sh use stable

# Install ruby and sass
apt-get install ruby
gem install sass

# Download and install pump controlling software
git clone https://github.com/FullR/pump-dashboard
cd pump-dashboard
npm install

