#!/bin/bash

# Run this after flashing the Beaglebone with Debian

# update
apt-get update

# install node dependencies
apt-get install -y gcc g++ clang

# build and install node
git clone https://github.com/nodejs/node
cd node
./configure
make
make install

# Install ruby and sass
apt-get install ruby
gem install sass

