#!/bin/bash

if [ "$BEAGLEBONE" = "true" ];
then
  PROD=true
  echo "Compiling for Beaglebone (production)"
else
  PROD=false
  echo "Compiling for desktop (development)"
fi

gcc ./bbb-gpio-util/index.c -o server/gpio.exe -D"PROD=$PROD"
